# Generated by Django 3.2.6 on 2021-09-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_training_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
