# Generated by Django 3.2.6 on 2021-09-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.exercise'),
        ),
    ]
