# Generated by Django 3.2.5 on 2021-09-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_exercise_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='training',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='user',
        ),
    ]
